// <auto-generated />
using BackgardenBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackgardenBlazor.Migrations
{
    [DbContext(typeof(SprinklerContext))]
    partial class SprinklerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BackgardenBlazor.Models.SprinklerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GpioPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sprinklers");
                });
#pragma warning restore 612, 618
        }
    }
}
